trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: ls -R
  displayName: 'Show project structure'

- task: Maven@4
  inputs:
    mavenPomFile: 'Javateam-DarchetypeArtifactId=maven-archetype-quickstart/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean install -DskipTests'
